# Mod Properties
mod_id=thermal
mod_name=Thermal Core
mod_version=11.0.8

# Platform Properties
java_version=21
mc_version=1.21.1
neo_version=21.1.218

# Dependency Properties
cofh_core_version=11.0.3
cofh_core_max_version=11.1.0

jei_version=19.27.0.340
curios_version=9.5.1+1.21.1
patchouli_version=1.21.1-92-NEOFORGE

# Publishing Properties

# Options: alpha, beta, release
release_type=beta